# src/main/resources/application.yml
okta:
  oauth2:
    issuer: https://dev-npa7aptydh7mjelc.us.auth0.com/
    client-id: Bo4pkCKUiazN7TxzrCP7qcjZJQrJYg1y
    client-secret: Pt977oPqTCMYCgclkSKWN4_2yniOY0_5QvZ_sOxfIvYWs11W-Tfvu5C-FZYVSre9