# src/main/resources/application.yml
okta:
  oauth2:
<<<<<<< HEAD
    issuer: https://dev-zstcmnbd5qzwv4cu.us.auth0.com/
    client-id: fCFXhsT4Vah1zAvLEaAOmRIiYNpgQAKN
    client-secret: 8PO3dCauPKk5Yej89pI5b64MZTgwV0FnMH2V37-lL9qXvekMrMddhKNl0JsXMP9w


=======
    issuer: https://dev-npa7aptydh7mjelc.us.auth0.com/
    client-id: Bo4pkCKUiazN7TxzrCP7qcjZJQrJYg1y
    client-secret: Pt977oPqTCMYCgclkSKWN4_2yniOY0_5QvZ_sOxfIvYWs11W-Tfvu5C-FZYVSre9
>>>>>>> bec62815c406a27a7d3d0431483f1cee8fc532af
